[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./node_modules/.bin/prisma migrate deploy; node dist/server.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 1
