[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./node_modules/.bin/prisma db push --skip-generate --force-reset && node dist/server.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 1
